src/shared/parameters/Mapping.js, src/shared/parameters/ParameterResolver.js, src/shared/parameters/createParameters.js, src/utils/is.js, test/modules/components.js
Shamelessly steals @Rich-Harris's fixes for #1566 and adds support for forcing resolution on ambiguous reference mappings (twoway binding issue reported by @anton-ryzhov in #1585).
=> gh-1566 take 2

src/shared/parameters/Mapping.js, test/__tests/components.js
This fixes #1645. I'm not 100% positive that this is the correct resolution for this, but it does work. Is there a better place to handle this and/or is there another corner case to cover?
Hat tip to @anton-ryzhov again for an excellent test case!
=> Fixes computations referencing mappings that throw when the mapping resolves

src/Ractive/static/adaptors/magic.js, src/viewmodel/prototype/clearCache.js, src/viewmodel/prototype/mark.js, src/viewmodel/prototype/set.js
@Madgvox I'm afraid #1641 caused 41 tests to fail! Totally my fault that it wasn't caught - in the process of updating the build/test scripts to not use grunt, I forgot to put `set -e` at the top of the scripts, which meant that Travis didn't bug out when the tests failed.
So I've had to revert the change. But I agree that double negatives are confusing - I figured that an easier way to get the tests to pass again would be to keep everything as it was, but replace `dontTeardownWrapper` with `keepExistingWrapper`.
Going to merge this immediately as there's currently no http://cdn.ractivejs.org/edge/ractive.js
=> Revert 1641

package.json
See #1672. Probably makes sense for the edge version to reflect the future rather than the present. Anyone have any objections (i.e. could it break anything)?
=> bump edge version -> 0.7.0-edge

src/parse/converters/mustache/readPartialDefinitionSection.js, src/parse/converters/mustache/readYielder.js, test/__tests/yield.js, test/gobblefile.js
=> allow inline partials, and named yields, to have hyphenated names

package.json
Did an `npm install` after `rm -rf node_modules` and `npm cache clean` and `npm run build` failed missing phantomjs. Any reason it shouldn't be in the dev dependencies?
=> Add missing package.json entry for phantom.js

src/Ractive/config/custom/css/transform.js, src/Ractive/initialise.js, src/virtualdom/Fragment/prototype/init.js, src/virtualdom/items/Component/initialise/createInstance.js, src/virtualdom/items/Element/prototype/init.js, src/virtualdom/items/Element/prototype/render.js, test/__tests/css.js
Aside from the bug (#1703) this fixes, I think I prefer this approach anyway - CSS IDs (i.e., the unique IDs of component constructors that have encapsulated CSS) are passed down from fragment to fragment until they get applied by an element. Seems like the correct way to do it, rather than the slightly hacky approach of each element testing whether its parent element is the component's root element.
=> fixes #1703 - encapsulated styles are forwarded to components until they can be applied

src/parse/converters/expressions/primary/readReference.js, test/testdeps/samples/parse.js
Surprisingly, not a regexp literal bug; just a typo.
=> fix root reference method call parsing

README.md, package.json, scripts/build.sh, scripts/test.sh
This should fix #1706 with the caveat that, at least on my machine, you have to modify the phantomjs wrapper script on windows to get it to actually run.
`npm run` on windows apparently uses CMD, so this adds an `sh` in front of the commands to get them to run with the npm runner. This also switches the gobble runner to the default `start` script.
The build was dying if the build folder wasn't present, so this adds a check for that as well.
=> More cross-platform friendly build stuffs

src/virtualdom/items/shared/Resolvers/ExpressionResolver.js, test/__tests/computations.js
Fixes #1728
This keeps the unique string generator from replacing '_[0-9]+' with the undefined if the number is greater than number of references for the expression. Is that the most appropriate fix?
=> Keep expression mangling for caching from messing with non-reference _things

src/viewmodel/prototype/map.js
Hi,
The keypath was undifined at this point, causing an uncatched exception/error.
This is the alternative fix for #1721, more general than the previous fix  #1724.
Cheers,
Arnaud
=> Guard for undefined keypath (bis)

src/parse/converters/readMustache.js, src/parse/converters/readText.js, test/testdeps/samples/parse.js
This fixes #276, which was closed as wontfix. Our docs currently use handlebars, which supports escaping mustaches with '\', so this does the same for Ractive.
Feel free to close this one wontfix too. I just needed a brief distraction to clear my head, and none of the current open issues aligned with my mood correctly.
=> Support escaping mustaches in templates

src/parse/converters/element/processDirective.js, src/parse/converters/readElement.js, test/__tests/events.js
This throws a parse error if there is extra, non-space stuff beyond the last `)` on a method call event handler with the offending chars included in the message. The pos is slightly off because it's already moved to the end of the attr, but it's pretty darn close. I added a parser param for `processDirective` so that the appropriate `ParseError` can be generated.
fixes #1288
=> Add error for extra chars after method call event handler

src/viewmodel/prototype/applyChanges.js, test/__tests/computations.js
=> invalidate computations that depend on values upstream of changes

src/Ractive/config/custom/template/template.js
Added a new error message when non-string templates are passed in without a parsed-Ractive-template version.
Fixes ractivejs/ractive#1581
=> Fixing rabbit-trail-inducing error message

package.json
I'm not sure this is an issue or not.
After I built the project locally, when I tried to use Ractive via npm link, I found that I wasn't able to require() the module because there was no ractive.js file in the root package directory.
Are there other steps that happen pre-publish?  I couldn't find another script that looked like it would move build/ractive.js to the root directory.
=> Change main from ractive.js to build/ractive.js

src/Ractive/prototype/get.js, src/viewmodel/prototype/get.js, src/virtualdom/items/shared/Resolvers/ExpressionResolver.js, test/__tests/get.js
~~Some unanswered questions remain, see #1783~~
Only mappings are included on root gets from `ractive.get()` and when used as an input to an expression, `{{ JSON.stringify(this) }}`.
=> Include mappings and computations on root get

src/Ractive/prototype/observe/getPattern.js, src/Ractive/prototype/set.js, src/Ractive/prototype/shared/add.js, src/Ractive/prototype/toggle.js, src/shared/keypaths.js, test/__tests/add.js, test/__tests/toggle.js
This fixes the unexpected behaviour in #1604:
```js
// before
let items = [{ active: false }, { active: true }, { active: false }]
ractive = new Ractive({
data: { items }
});
ractive.toggle( 'items[*].active' );
console.log( items ); // [{ active: true }, { active: true }, { active: true }] // broken
ractive.toggle( 'items[*].active' );
console.log( items ); // [{ active: true }, { active: true }, { active: true }] // very broken
// after
let items = [{ active: false }, { active: true }, { active: false }]
ractive = new Ractive({
data: { items }
});
ractive.toggle( 'items[*].active' );
console.log( items ); // [{ active: true }, { active: false }, { active: true }]
ractive.toggle( 'items[*].active' );
console.log( items ); // [{ active: false }, { active: true }, { active: false }]
```
=> Allow wildcards to be used with ractive.toggle(), ractive.add() and ractive.subtract()

src/parse/Parser.js, src/parse/converters/element/readAttribute.js, test/testdeps/samples/parse.js
As well as fixing #1339 I snuck in a fix for how hard tabs are dealt with when reporting errors, so that the `^----` lines up with the actual error, whether you're seeing it in browser or on the command line
=> more informative error for broken attributes. closes #1339

src/Ractive/config/custom/data.js, test/__tests/components.js
The idea here is to ensure that people don't run into weird bugs in which an instance of a component accidentally mutates that component's default data, by suggesting the use of data functions instead of data objects.
I'm trying something slightly different here - printing example code to the console (ES6 template strings ftw!). Takes up a few lines, but is maybe more useful than trying to explain things, or send people to an explainer page on the docs.
Any thoughts?
=> encourage use of data functions with Ractive.extend()

src/utils/dom.js, src/virtualdom/items/Element/Attribute/prototype/update/updateClassName.js, src/virtualdom/items/Interpolator.js, test/__tests/render.js
Fixes #1825: situations where the DOM object properties like `.className` expect objects that can be converted via `toString`
=> Add safeToStringValue for objects with no toString method (gh-1825)

src/utils/log.js
The new debug welcome message take up a lot of real estate which gets tres annoying when your running live reload or otherwise refreshing browser. This reduces it to:
The full message is available if you expand the group (which works by clicking anywhere on that line).
`console.groupCollapse` has [good browser support](https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed#Browser_compatibility) and this falls back to `log` if not.
We might consider this pattern for some of the other lengthy messages that have code snippets, etc. attached to them.
=> Collapse welcome message to minimize spaminess

test/__tests/arrays.js, test/__tests/componentData.js, test/__tests/components.js, test/__tests/computations.js, test/__tests/elements.js, test/__tests/init/hooks.js, test/__tests/init/initialisation.js, test/__tests/misc.js, test/__tests/partials.js, test/__tests/transitions.js, test/__tests/twoway.js, test/__tests/yield.js
A few tests depend on monkey-patching `console.warn()`, which is a problem for IE9 as it doesn't have `console`. This PR wraps them in an `if ( typeof console !== 'undefined' && console.warn ) {...}` block.
=> put all console.warn-using tests inside a conditional, for benefit of IE9

src/virtualdom/items/Element/prototype/init.js, src/virtualdom/items/Partial/_Partial.js, src/virtualdom/items/Partial/getPartialTemplate.js, test/__tests/partials.js
~~Per #1838's discussion, this gets inline partials scoped back to their nearest Ractive instance. It does so by simply copying the partials from the element to the element root when the element is instantiated. This does have at least one potential issue that I can think of: non-rendered segments of the template can't contribute inline partials. I don't know if that's a bug or a feature. It kinda makes sense, but then the partial hangs around if the element is unrendered, which seems a little wrong. So, I could go either way on how to handle that:~~
1. ~~Read through the whole template when it is loaded and pull in any partials that don't exist down a component tree. This is roughly the same as the previous behavior.~~
2. ~~When the element is torn down, reset any partials that it …
=> Taking a swing at the inline partial shuffle

gobblefile.js, package.json, scripts/test.sh
This is a stopgap measure of sorts - esperanto needs a better API for overriding module contents (see https://github.com/esperantojs/esperanto/pull/141), and ultimately it'd be nice to have far more flexible custom builds, of which legacy/runtime are just two of many possible combinations.
But it fixes the regression introduced in 0.7.1 and means that people can continue to use `ractive.runtime.js`.
=> fix #1860 - ensure `parse` is declared

src/Ractive/config/config.js, src/utils/log.js
Couple of issues that came up with #1885:
1. isStandardKey was returning true for object prototype props like `constructor`.
2. if `log` `options` was undefined, `options.ractive` was failing.
=> Use hasOwnProperty, prevent log from undefined error

CONTRIBUTING.md, README.md
We got a black mark on a security report (see #1897) for not having a security response program. As a starting point, we should make it clear that people are encouraged to report security vulnerabilities, and by asking people to add `[security]` to issue titles we can ensure they're appropriately prioritised.
One thing this *doesn't* give us is a way for people to report vulnerabilities privately. Is that something we also need to consider?
=> add notes on reporting security vulns

src/Ractive/config/custom/template/parser.js
I couldn't reproduce #1908 locally. But assuming that `textContent` is the problem, hopefully this is the solution.
=> use template.innerHTML in IE8, use ES6 template strings etc

src/virtualdom/items/Element/Binding/ContentEditableBinding.js, test/__tests/twoway.js
This bases `ContentEditableBinding` on `GenericBinding` so that it also gets working lazy and twoway directive handling. I'm not sure why it wasn't based on it to begin with... anyone else know why?
=> Fix contenteditable binding laziness

src/view/items/Section.js, src/view/resolvers/ExpressionProxy.js, test/testdeps/samples/render.js
I've fixed a couple of bugs where an undefined unless block won't work. And an undefined model would throw a script error.
=> Fix bugs with unless sections and undefined models

src/utils/dom.js, src/virtualdom/items/Element/prototype/render.js, test/__tests/elements.js
In reference to https://github.com/ractivejs/ractive/issues/2043
This code change assumes the user will put a static string value for the "is" attribute. I don't think it makes sense to allow dynamic mustaches for "is", since the whole node would need to be deleted and a new node created with the different typeExtension. Maybe Attribute$init() could just print an error and treat a dynamic mustache as a static mustache to avoid that complication.
Note: this (https://github.com/ractivejs/ractive/blob/master/CONTRIBUTING.md#pull-requests) says to run `grunt test`, but when I try that I get "Fatal error: Unable to find Gruntfile."
=> add support for custom element typeExtensions

src/view/items/element/Attribute.js, src/view/items/element/attribute/determineNameAndNamespace.js, src/view/items/element/attribute/getUpdateDelegate.js, test/__tests/render.js
This somehow got dropped with all the recent refactoring.
I stole the `determineNameAndNamespace` function directly from the 0.7.3 release.
=> Fix namespaced attributes, like xlink:href

src/events/fireEvent.js, src/parse/converters/element/processDirective.js, src/shared/createFunction.js, src/view/items/Component.js, src/view/items/Element.js, src/view/items/component/RactiveEvent.js, src/view/items/element/ElementEvents.js, src/view/items/shared/EventDirective.js, src/view/items/shared/EventHandler.js, test/__tests/events.js
Refactored out the event source (`DOMEvent`, `CustomEvent`) from `EventHandler` and added a `RactiveEvent` used to proxy the component instance events.
This gives full event handling capability to component events including method calls.
Right now, original instance event args are tacked on after component event arg (but original `event` arg is still first if it exists). Need to implement argument repackaging per [#1172 comment](https://github.com/ractivejs/ractive/issues/1172/#issuecomment-136159638).
=> Component events as first-class citizens

src/view/resolvers/resolveAmbiguousReference.js, test/__tests/components.js
Remarkably, simply deleting a few lines of code fixes #2108 without breaking any other tests
=> Prevent mappings leapfrogging local contexts

.gitignore, perf/tests/events.js, src/view/items/element/ElementEvents.js
I had a chance to investigate something I was curious about: the existing use of routing of DOM event handling through a common function and then calling a handler stored on the event node. 
Via the perf tests it didn't seem to make a difference, though @Rich-Harris  maybe you know something I don't, or it's an IE thing, or something like that? (Side note: Our perf tests don't run on firefox, due to number of interaction issues between iframe and main window)  
Removing it simplifies the code and we don't have to store state on the DOM nodes for events.
For event plugins, we have a closure anyway, so I added default inclusion of the `node` so plugin authors don't need to add it. Even if we need to keep the common `defaultHandler` we should keep this.
=> Simplify event code and perf test events

src/Ractive/config/custom/data.js, src/Ractive/construct.js, src/Ractive/helpers/getComputationSignature.js, src/Ractive/prototype/set.js, src/Ractive/prototype/teardown.js, src/utils/bind.js, src/view/items/shared/EventDirective.js, src/view/resolvers/ExpressionProxy.js, test/__tests/misc.js, test/testdeps/helpers/Model.js
This is a follow-up to #2111. Rather than binding functions to the current instance (or reusing existing bound function copies) in situations like `{{foo()}}` and `on-click='set("bar",foo())'` (where `foo` depends on `this`) at the point of *getting* them, we bind them at the point of *setting* them (or upon initialisation). This is cheaper (it only needs to happen once) and cleaner (we don't need to track bound copies and clean them up later).
The only situation where it might be a problem is if someone is using a non-POJO as their root `data` object, which is already strongly discouraged (and warned about in debug mode).
=> Bind functions on init/set

.editorconfig, src/Ractive/initialise.js, src/model/Computation.js, src/model/ComputationChild.js, src/model/Model.js, src/view/items/Section.js, src/view/resolvers/ExpressionProxy.js, test/__tests/arrays.js, test/__tests/computations.js
I believe this is the correct fix for #2069 – the `ExpressionProxy` class, which acts as an interface between the view and a `Computation`, should behave similarly to the `ComputationChild` in #2122 (this branch is based off that PR's branch). This ensures that `fn` in `{{#each items}}{{fn(this)}}{{/each}}` is never called with no-longer-extant memnbers of `items`.
=> Alternative #2069 fix

.editorconfig, src/model/Model.js, src/view/items/Section.js, test/__tests/computations.js
turns out that we have to check if it's a computed property when getting (not on the model.joinPath) and lazily compute the value (not when joining it) - otherwise this.value is always undefined (because it never even computes) ...
this is because the computed property returns an object.
just thought of something: it could potentially not resolve if the computed property returns a deep object (and the template references at least 2 levels inside). I dunno
=> Computed parent

.editorconfig, src/Ractive/initialise.js, src/model/Computation.js, src/model/ComputationChild.js, src/model/Model.js, src/view/items/Section.js, src/view/resolvers/ExpressionProxy.js, test/__tests/computations.js
This follows up @heavyk's work in #2117. From it, I came to realise that `{{foo.bar.baz}}` where `foo` is a computed value is actually a totally different beast to `{{foo.bar.baz}}` where `foo` is a regular value. With regular values, if `foo` is changed but `foo.bar.baz` ends up the same, dependants of `foo.bar.baz` are left alone, meaning that part of the view tree doesn't become 'dirty'. Computed values work the other way round – if their dependencies change, they don't recalculate immediately but instead always notify their dependencies and children of the change, and then *later* (when observers are dispatched, or the view is updated) recalculate *if necessary*.
So given that `foo.bar.baz` and `foo.bar.baz` can do two totally different jobs, depending on what sort of thing `foo` is, …
=> Children of computed values

src/model/specials/KeypathModel.js, test/browser-tests/partials.js
This looks a little weird, but it kinda makes sense that keypath models should hand back their value as their keypath. The other route I looked at, using `get()` from `ExpressionProxy`, causes other tangential breakage. Does this look right?
=> implement getKeypath on keypath models - fixes #2164

src/view/items/Component.js, test/browser-tests/components/data-and-mappings.js
The issue here is that the component gets an implicit mapping to a particular model nested on its parent and, on rebind, it finds the old implicit mapping to the now wrong model and rebinds to it. This just empties the mappings on rebind to let the re-resolution happen naturally. This is another one for which I'm not positive that this is the best approach. Is there a better way to handle it?
Thanks to @ISNIT0 and @heavyk for test cases and taking a swing at this. It was deep and interesting spelunk through the internals of shuffling.
=> clear mappings on component rebind to avoid shuffling issues - fixes #2147

src/parse/converters/expressions/shared/readRefinement.js, src/parse/converters/mustache/readPartial.js, test/browser-tests/partials.js
I ran into this in a late night coding session. The fix, more-or-less as suggested by @Crisfole, is to simply not allow whitespace in refinements if the relaxedNames flag is set. Any objections?
For reference in #1880, whitespace is normally allowed in refinements because all of the following are equivalent in js:
```js
const foo = { bar: 'baz' };
foo.bar;
// and
foo  .  bar;
// and
foo.
bar;
// and
foo
.bar;
// and
foo    ['bar'];
// and
foo
[
'bar'
];
```
=> Relative partial context - #1880

src/parse/_parse.js, src/parse/converters/readElement.js, src/view/items/Element.js, src/view/items/Interpolator.js, src/view/items/Text.js, src/view/items/Triple.js, src/view/items/createItem.js, src/view/items/element/binding/selectBinding.js, src/view/items/element/specials/Textarea.js, test/browser-tests/forms.js, test/browser-tests/twoway.js
There are a number of textarea issues outstanding, and I think this addresses them all in a fairly sane manner. #2011 #2063 #2099 #2197 #2198
* `textarea`s are treated like interpolated script tags by the parser, so content html is rendered as-is if there are no bindings.
* `textarea`s with a single non-static interpolator as content and that don't also have a value attribute are bound as if the content interpolator was the value binding
* `textarea`s with template content that updates (`bubble`s) will set their node value to their fragment `toString` after the runloop turn
=> Various textarea content changes: binding, updates, etc - RFC

src/Ractive/prototype/shared/makeArrayMethod.js, src/model/Model.js, src/parse/converters/expressions/primary/readReference.js, src/shared/keypaths.js, src/utils/getPotentialWildcardMatches.js, src/view/items/shared/EventDirective.js, src/view/resolvers/ReferenceResolver.js, src/view/resolvers/resolveAmbiguousReference.js, src/view/resolvers/resolveReference.js, test/__support/js/samples/render.js, test/browser-tests/misc.js
__Probably post 0.8__
This is a fairly requested feature that I believe was present at one point and removed due to complexity. After the massive awesome `Model` changes from @martypdx and @Rich-Harris I think a lot of the complexity has been reduced. I needed a mental break from the day job, so I figured I'd take a swing at this.
All of the tests pass, and the following now works as you'd expect:
```html
{{ foo\.bar }} {{ foo.bar\.baz }} {{ foo.bar.baz }}
{{ .['foo.bar'] }} {{ foo['bar.baz'] }} {{ foo['bar']['baz'] }} {{ foo[key] }}
```
Data:
```js
{
'foo.bar': 'works1',
foo: { 'bar.baz': 'works2', bar: { baz: 'still works' } },
key: 'bar.baz'
}
```
Output:
```
works1 works2 still works
works1 works2 still works works2
```
If you see anything I missed or screwed up horribly or have some …
=> First swing at escaping . in keypaths - RFC

src/Ractive/prototype/resetPartial.js, src/view/items/Partial.js, test/browser-tests/partials.js
Partial names should always take precedent over partial name resolutions. I think that should also apply to resetting a partial name that resolved dynamically initially. See #2185, which this should fix.
=> Check ref name along with resolved name when resetting partials

src/view/items/element/binding/CheckboxNameBinding.js, src/view/items/element/binding/RadioBinding.js, src/view/items/element/binding/RadioNameBinding.js, src/view/items/element/binding/getBindingGroup.js, test/browser-tests/twoway.js
Named checkbox bindings where more than one checkbox shared a value were not handled. This adds support for them. It also moves the group registry from a private object in binding group onto a property of the model so that components are guaranteed to get the same group if they share a model even if mappings or some other factor make the hash not equal. This should fix #2163.
I'm 99% sure this is correct, but I would like a sanity check on both functionality and construction.
I removed the RadioBinding TODO to move to binding group because they have no model in which to store the group.
=> Name bound checkboxes with duplicate values and crossing component boundaries - #2163

src/parse/converters/expressions/primary/literal/objectLiteral/keyValuePair.js, src/parse/converters/expressions/shared/readKey.js, test/__support/js/samples/parse.js
`{ foo, bar, baz: 'bat' }` because I'm used to doing it everywhere else now. Opinions?
=> ES2015 object literal property shorthand

src/Ractive/static/adaptors/magic.js, src/model/Model.js, src/shared/keypaths.js, src/view/resolvers/ReferenceExpressionProxy.js, test/__support/js/samples/render.js, test/browser-tests/misc.js
This PR addresses the following issues:
1. Multiple escapes in a single keypath - `ractive.get('foo\\.bar\\.baz')` now works correctly (was interpreted as `ractive.get('foo\\.bar.baz')` before).
2. `{{foo['bar.baz']}}` updates on `ractive.set('foo.bar\\.baz')`
3. `$`'s in keypaths aren't incorrectly converted to `.`
4. Backslashes can also be escaped, so calling `ractive.set('foo\\\\.bar', 1)` is the same as `ractive.set({ 'foo\\': { bar: 1 } })`
=> More robust . escaping

src/view/items/element/Decorator.js, test/browser-tests/plugins/decorators.js
update Decorator dynamicName and dynamicArg fragments when dirty, fixes #2213
=> Update dirty status on decorators - fixes #2213

src/view/RepeatedFragment.js, test/browser-tests/render/misc.js
This looks for the next iteration after the target index that actually has a node. The behavior in edge now makes fragments looking for the next node append instead of inserting if the next iteration doesn't actually have a node.
=> Skip iterations without nodes when looking for next node in repeated sections - #2234

src/global/TransitionManager.js, src/global/runloop.js, src/view/items/Element.js, src/view/items/element/Decorator.js, test/browser-tests/methods/observe.js
Fixes #1869.  (Re)moving the `TransitionManager.init` into `.start` seems to do the trick.
Also pruned some uncalled code and now Transition Manager doesn't need to know about decorators.
=> Remove non-transition nodes from DOM before calling deferred observers (#1869)

src/view/items/element/Decorator.js, src/view/items/element/ElementEvents.js, test/browser-tests/events/custom-proxy-events.js, test/browser-tests/plugins/decorators.js
I went for the middle ground of `warnOnce` on decorator and event plugins. Fixes #2246 
You could make arguments for either `warnOnceIfDebug` and `fatal`. Thoughts?
=> Restore console log of missing decorators and events

src/Ractive/prototype/observe.js, src/view/RepeatedFragment.js, test/browser-tests/methods/observe.js
This is my patch from #2222 with tests added.
First, if an array with object children is shuffled, then the pattern observer will fire for all of the keys. It seems like it should only fire on the observed keys, so this adds shuffle support that does that.
Second, if an observer makes a change that causes a shuffle, and the observer fires more than once, the repeated fragment refuses to shuffle more than once. This also adds support for the multiple shuffles per runloop to repeated sections by mapping the original new indices through the accumulated shuffles.
=> Shuffling pattern observers and repeated sections - #2222

src/config/types.js, src/parse/converters/mustache/readAliases.js, src/parse/converters/mustache/readSection.js, src/view/RepeatedFragment.js, src/view/items/Alias.js, src/view/items/createItem.js, src/view/resolvers/resolveAmbiguousReference.js, test/browser-tests/aliases.js
__Probably post 0.8~~, not ready for merge, and no tests yet~~__
This is one of those things that pops up now and then as a little bit surprising: setting context with `with` isn't really bidirectional (#1353). There has been a proposed syntax to address that `{{#with foo.bar.baz as v1, lah.dee.dah as v2}}`, and this is my attempt to see what it would take and how it would work. What this does is introduce a new step in parsing sections, a new node type, and another step in ambiguous reference resolution to achieve aliasing within a branch of a template.
The parsing step sits between block name and expression parsing. It looks for aliases in the form `[expression] as [non-path ref]` with optional additional `,` separated aliases if the section type is a `with`. If aliases are found, they …
=> Template aliasing - RFC

src/view/items/Yielder.js, test/browser-tests/components/yield.js
It looks like the special component handling during bubble keeps the yield fragment from getting handled in the runloop. This overrides `bubble` on `Yielder` to register the fragment with the runloop so that the fragment updates and isn't left in a dirty state after the update. Does that sound right?
=> Register yield fragments during bubble - fixes #2235

src/parse/converters/element/processDirective.js, src/view/items/shared/EventDirective.js, test/browser-tests/events/dom-proxy-events.js, test/browser-tests/events/method-calls.js
Fixes #2253. Component event directives now append existing arguments by default:
`<widget on-foo='bar' on-qux:'bizz:{{buzz}}'/>`
will now fire `bar` and `bizz` with original arguments from `foo` and `qux` appended to any supplied arguments (added to value of `{{buzz}}` in `on-qux` firing of `bizz`).
Also makes `...argument` in method calls more robust by allowing inclusion of spread at end of method allowing other arguments to be included:
`<widget on-foo='bar( "foo", ...arguments )'/>`
=> Append arguments automatically on re-fired events, more robust arguments spread in method calls

src/view/items/Element.js, test/browser-tests/render/elements.js
It's a special case for `<option>` – don't know how far we want to go down this road. Though it could be extended to other text-only elements easily enough – does anyone know if there are any other than `<option>`?
Fixes #2242 (sort of)
=> throw if element is created inside an <option>

src/view/resolvers/resolveReference.js, test/browser-tests/components/data-and-mappings.js
In a component, in `{{#with some.mapped.path}}{{~/local}}{{/with}}`, `local` is trying to resolve using the mapped context root instead of the component root. I believe the correct behavior would be to use the component root instead, right?
=> Root refs in components should use component viewmodel not context

src/model/Computation.js, test/browser-tests/shuffling.js
Computations are one of those weird dep/child hybrids that automatically inherit the model shuffle, but since they aren't really shuffle-able, they should not have a shuffle method. This overrides the prototype shuffle property with undefined during construction and fixes #2267 and #2269. Thoughts?
=> Computations are models that don't shuffle

src/view/items/element/attribute/getUpdateDelegate.js, test/browser-tests/forms.js
This adds a check for text inputs so that they don't get set to `undefined` but get a "safe" string instead. Thoughts?
=> Update text input types with safe string value

src/parse/converters/mustache/readPartial.js, test/browser-tests/partials.js
This adds support for `{{>foo bar as bat, bip as bop}}` -> `{{#with bar as bat, bip as bop}}{{>foo}}{{/with}}` like the existing context shortcut for partials. Any objections?
=> Support for aliasing shortcut for partials - part of #2298

src/utils/html.js
As discovered in #2291, Ractive doesn't currently allow any characters outside of the BMP because `String.fromCharCode` doesn't support anything outside the BMP. Things are getting better though, so this checks to see if `String.fromCodePoint` is available, and if it is, allows characters from the SMP and SIP as well.
I don't know if it would be better to wholesale allow the other planes, as they are mostly undefined/private(?) beyond the SIP.
Also, I didn't add a test here because it seems straightforward enough and I don't want to tempt the wrath of the elder browsers and engines by including a unicode character from beyond the reasonable scripts. If this PR is acceptable but needs a test, I can take a swing at it. Suggestions or pushes are also more than welcome.
For reference: …
=> Add support for unicode characters in the SMP and SIP

src/model/RootModel.js, src/model/specials/GlobalModel.js, src/model/specials/RactiveModel.js, src/parse/converters/expressions/primary/readReference.js, src/view/resolvers/resolveReference.js, test/browser-tests/misc.js
__Post 0.8__
This adds two new special refs, `@ractive` and `@global`, that give access to the current Ractive instance and the global object (`window` in a browser environment). Unlike other special refs, these support accessing child paths.
Well, for `@global`, it's an outstanding feature request from #1997. Anything in global scope can now be used in the template, which is particularly handy for using external libraries. It's also nice for integration into pages that aren't controlled entirely by Ractive. Two-way binding for child paths also works nicely. There is a single shared model that controls access to the global from within Ractive.
For `@ractive`, as mentioned in several issues recently, it's nice to be able to use functions that are added directly to the Ractive instance in a …
=> @global and @ractive special refs - RFC

src/Ractive/construct.js, src/Ractive/prototype.js, src/Ractive/prototype/link.js, src/Ractive/prototype/teardown.js, src/Ractive/prototype/unlink.js, src/view/items/Component.js, test/browser-tests/methods/link.js
This is a port of #1722 to the lovely new Model replacement for viewmodel and friends. It basically allows you to create a link between two keypaths that makes them equivalent, which is particularly handy for master-detail type scenarios. For instance:
```html
<ul>
{{#each items}}
<li on-click="link(@keypath, 'current')">{{.name}} {{.number}}</li>
{{/each}}
</ul>
<button on-click="push('items', {})">Add</button>
<div>
Name: <input value="{{ current.name }}" /><br/>
Number: <input value="{{ current.number }}" />
</div>
```
This passes the tests that were added with #1722, but there probably need to be a few more. I would greatly appreciate any feedback on concept, construction, or further tests.
=> Symlinks for keypaths - RFC

src/Ractive/prototype/resetTemplate.js, src/view/items/element/Decorator.js, test/browser-tests/components/data-and-mappings.js, test/browser-tests/components/misc.js, test/browser-tests/computations.js, test/browser-tests/events/touch-events.js, test/browser-tests/methods/reset.js, test/browser-tests/misc.js, test/browser-tests/partials.js, test/browser-tests/plugins/adaptors/basic.js, test/browser-tests/plugins/decorators.js, test/browser-tests/render/mustache-compliance/all.js, test/browser-tests/render/output.js, test/browser-tests/twoway.js
When running the test suite you get a console full of warnings. It's annoying. They should either be suppressed, or considered part of the test. This PR does that
=> Remove test warnings

src/parse/converters/readExpressionOrReference.js, test/__support/js/samples/render.js
This makes it possible to have things like `{{new}}`, since sometimes you don't control the shape of your data. Good idea? Bad idea? Would fix #1934
=> Allow keywords as references

src/Ractive/prototype/observe.js, src/model/Computation.js, src/model/Model.js, src/model/RootModel.js, test/browser-tests/methods/observe.js
Follow-on to #2296, I started testing cases around #1990 being able to use observers faithfully for component root and `*` wildcard I found a number of issues around root observers and `'*'` observers:
* Template expressions with internal `@(..` keypaths are no longer included 
* Both `*` and root observers use correct component-relative keypaths
* Adding new properties works correctly
=> Better, 'onchange' worthy observers at root/wildcard *

src/Ractive/prototype/get.js, test/browser-tests/components/data-and-mappings.js
The default resolution path in `Ractive.get` isn't currently checking isolation before trying to create a mapping using the parent fragment context as a jumping off point. Naturally, that will always resolve upstream, so this adds a check for isolation before taking that path.
=> Prevent isolated components from accessing ancestor data via API - #2335

src/global/TransitionManager.js, test/browser-tests/plugins/transitions.js
This fixes #2310. The issue is that the transition manager starts and completes its outros before the deferred observers fire, and the deferred observers cause nodes to be removed and their transition manager is a child of the already completed original transition manager. So when the second round goes to detach, they never do because the parent transition manager is already done.
This skips the parent queue if the parent is already done and just goes ahead with the detachment. Would it be more appropriate to move the transition manager start to after the deferred observers fire?
@JonDum, can you try this out and let me know if it definitely fixes your problem?
@gaelicmichael, if you have a few spare cycles, could you try this as an alternative for the fixes in #2284?
I can provide test …
=> Make sure nodes queued to detach after transition has started actually get detached - #2310

src/view/RepeatedFragment.js, test/browser-tests/render/css.js
Another regression – the `data-ractive-css` IDs weren't getting passed down through `{{#each}}` blocks, causing errors with scoped CSS. [Demo](http://jsfiddle.net/rich_harris/2f2Lek77/)
=> pass CSS IDs down through {{#each}} blocks

src/view/items/element/Transition.js, test/browser-tests/plugins/transitions.js
Regression via typo: the context of a transition function should be the instance in question
=> ensure correct transition context

src/view/items/element/specials/Form.js, test/browser-tests/forms.js
Turns out the Form item was missing its call to super in unrender. I didn't event know there was a Form item :smile:. See #2352.
=> Forms should unrender properly - #2352

src/view/items/partial/getPartialTemplate.js, test/browser-tests/partials.js
Per #1445, if you have a partial script with another partial inlined, the inlined partial is lost. This allows the inlined partials to be added to the ractive partials store if there aren't already partials with the same names.
=> Let runtime parsed partials contain other top-level partials - #1445

src/model/Computation.js, src/model/Model.js, src/view/RepeatedFragment.js, src/view/items/shared/Mustache.js, src/view/resolvers/ExpressionProxy.js, test/browser-tests/computations.js, test/browser-tests/methods/splice.js
There are two bugs showcased in #2321.
~~The first is that computations are currently triggered again during shuffling for elements that should no longer be rendered afterwards. Since expression proxies are also kinda-fragments, I added a way to rebind them too and added a check in mustache that detects a rebindable model (isExpression and has a rebind) and calls it instead of replacing the model. That resolved the issue of calling unresolvable computations for the test case. It also seemed to render the discard checks during shuffle obsolete, so I pulled them out.~~ Yep... caused by the second one...
The second is that object iteration, as opposed to array iteration, was not allowed to rebind because it was only looking for array-like thinks being iterated. Object aren't arrays, so they …
=> Allow expression proxies and object iteration sections to rebind - #2321 - RFC

src/model/RootModel.js, src/view/items/Partial.js
One of the things that @sabob dug up in #2366 was that lots of resolution in a heavily iterated template was unnecessarily creating full `RootModel` exports just to check for presence of keys. This works around that by implementing the whole `has` method for `RootModel`.
I was going to make the full export opt-in only by adding a flag to `RootModel.get` and possibly `Ractive.get`, but that breaks the assumption that `model.get` can be called for any model anywhere. Thoughts?
=> Avoid exporting all reachable keypaths from rootmodel when using has - #2366 - RFC

src/parse/utils/stripStandalones.js, test/browser-tests/render/misc.js
Turned out to be less painful than I thought it would. It was just a `\s` where `[ \t\f\r\n]` was called for instead because `\s` matches `&nbsp;` where the other class does not. Fixes #2327.
=> Don't count non-breaking spaces as whitespace when stripping space - #2327

src/Ractive.js, src/Ractive/config/custom/css/css.js, src/Ractive/prototype.js, src/Ractive/prototype/toCSS.js, src/Ractive/render.js, src/global/css.js, src/utils/id.js, test/browser-tests/getCSS.js, test/browser-tests/methods/toCSS.js, test/node-tests/getCSS.js, test/node-tests/index.js, test/node-tests/toCSS.js
Exposes the CSS generated by Ractive via a new toCSS method, plus a few cleanups and tests here and there. Since there wasn't a PR (just a commit on some fork), decided to create one.
ToDo:
=> Adding toCSS method WIP - RFC

src/Ractive/prototype/animate.js, test/browser-tests/methods/animate.js
`ractive.animate(...)` was failing to return a promise in cases where it wasn't possible to interpolate values, causing unexpected behaviour. This PR fixes it
=> ractive.animate should always return a promise, even if no animation

src/Ractive/prototype/set.js
Chrome was barking at me about `Ractive.prototype.set` being deoptimised ('ForInStatement with non-local each variable'). This fixes it
=> use local variable with for...in to avoid deopt

src/global/runloop.js, src/model/Computation.js, src/view/Fragment.js, src/view/items/Alias.js, src/view/items/Component.js, src/view/items/Element.js, src/view/items/Interpolator.js, src/view/items/Partial.js, src/view/items/Section.js, src/view/items/Triple.js, src/view/items/Yielder.js, src/view/items/element/Attribute.js, src/view/items/element/ConditionalAttribute.js, src/view/items/element/Decorator.js, src/view/items/shared/EventDirective.js
This is a really funky one... basically, the binding causes a bubble while inside update. Since the fragment is still dirty during the update, the bubble doesn't pass the updating fragment. Then the update completes and marks the fragment as clean, but it now has dirty children that won't get registered until something causes them to bubble again.
Making the dirty flag get reset at the beginning of the update fixes that, but it also breaks some assumptions about how things flow in the runloop. So, this takes the existing process, which allows new fragments to be registered _after_ the fragments are processed, and lets new fragments (or the same ones) be registered _during_ the processing. That messes up assumptions about how observers will fire, so the same thing is done with them.
There …
=> Fragments and bubbling while also updating - #2406 - Review

src/Ractive/initialise.js, src/Ractive/static/getNodeInfo.js, src/view/Fragment.js, src/view/RepeatedFragment.js, src/view/helpers/gatherRefs.js, src/view/items/Component.js, src/view/items/Element.js, src/view/items/shared/EventDirective.js, test/browser-tests/components/misc.js, test/browser-tests/methods/splice.js, test/browser-tests/misc.js
Template refs for indices and keys are currently forwarded along through the fragment hierarchy as it gets created. This seems like basically trading performance for memory, which is fine, but it also introduces a maintenance burden for splicing. That maintenance is not currently being done per #2399 and #2400.
This PR drops the forwarding of refs through and instead looks them up when needed e.g. when an event is fired or when `Ractive.getNodeInfo` is called. I looked briefly at trying to keep the `indexRefs` and `keyRefs` objects up to date when a shuffle happens, but it looked like more code than it's worth for the two places they're actually used. The only potential downside is that gathering the refs for a very very deep template on event firing might add a very slight delay to the …
=> PRIVATE BREAKING: Look up template refs for node info and events on the fly - RFC

src/view/Fragment.js, src/view/RepeatedFragment.js, src/view/items/Alias.js, src/view/items/Component.js, src/view/items/Partial.js, src/view/items/Section.js, src/view/items/Yielder.js
When searching for the next node in a complex repeated fragment in order to insert a new iteration, edge is currently checking each element from the parent, each element is checking the parent, and so forth until the browser gives up.
This adds a flag to `firstNode` that, when set, tells it not to punt to the parent if it can't find a node for itself. That avoids repeated sections calling children that call it back.
Thoughts?
_I fat-finger tab-enter submitted this a little early... sorry_
=> Avoid exponential firstNode search - #2395 - Review

src/view/resolvers/ReferenceExpressionProxy.js, test/browser-tests/twoway.js
This is another slightly funky one. Basically, binding to a child of a reference expression creates a branch off the reference expression proxy that doesn't notify its source when it changes. This adds a special `ReferenceExpressionChild` model that finds its source model during `applyValue` and calls `applyValue` on it too.
Thoughts? I couldn't come up with a better way™, but that certainly doesn't mean that there isn't one.
=> Keep primary model in sync with reference expression children - #2408 - Review

src/view/RepeatedFragment.js
For background, see #2366
There are two scenarios to arrive in `updatePostShuffle`: `merge` and `splice`(ish things). The current algorithm is a sort-of hybrid for handling merges and splices that ends up detaching and re-attaching everything past a certain point. The detaching and re-attaching is required for merges, which tend to be more of a jumble, and the 'past a certain point' is aimed at splices, which operate on a single contiguous region.
For the delete test on which Ractive performs poorly, part of the performance issue seems to be caused by detaching and re-attaching _every_ element in the repeated fragment. This adds a check to see if everything remains sequential, and if it does, avoids detaching and re-attaching iterations that are already in place. New iterations are …
=> Add a splice-oriented handler for updatePostShuffle - RFC/Review

src/view/Fragment.js, src/view/RepeatedFragment.js, src/view/items/Section.js, test/browser-tests/twoway.js
This fixes #2424 and maybe a few others... __not ready - no tests__
In #2407, the dirty flag got bumped around such that happenings during an update that should cause a bubble actually caused a bubble. That was also keeping an update from running during an update, which apparently causes all sorts of bizarre behavior. This adds a `updating` flag to RepeatedFragment and Section to keep them from getting out of whack whilst updating content with bindings that cause further updates. I have to ponder this a bit more, but should all items have an update guard, or just fragments, or just what I have here?
=> Keep update from running in nested runloops for repeats and sections - #2424

src/view/items/element/Attribute.js, test/browser-tests/shuffling.js
The test case from #2422 involves rebinding an attribute value that depends on an `@index` ref, but since attributes aren't sensitive to the change (they just wholesale unbind and bind), they never get notified of a change during the shuffle. This adds a step that grabs the value at the start of rebinding and checks it against the value after rebinding. If the value is not strict equal, it bubbles.
An alternate fix would be simply: `rebind() { if ( this.fragment ) this.fragment.rebind(); }`. It seems to work, but for some reason it didn't feel right (I think stepping through too much code may be throwing me). I'm not wild about calling `getValue` twice on every attribute shuffle, so if there's no reason not to do that, it would probably be better.
Thoughts?
=> Check attribute values while shuffling to see if an update is in order - #2422 - RFC

src/view/items/element/specials/Select.js, test/browser-tests/select.js
It seems that with the runloop stuff that's happened recently, it has become unnecessary and detrimental to do a deferred sync of the value in a select element after a bubble. It looks like the combo of only using dirty flags for cleanliness and letting the runloop detect runloop triggered changes took care of the original case that made that necessary. Does that sound right?
With this patch, the options fragments in the example in #2428 are updated correctly.
=> Skip deferred sync of select value - #2428 - RFC

src/view/items/Component.js, src/view/items/shared/Item.js, test/browser-tests/components/data-and-mappings.js
#2444 seems to be caused by two little issues:
1. complex mappings override bubble on their fragment to intercept change calls, but they don't also force the fragment to update before using its value to set the model. This adds an update in the bubble just before the model set to handle that.
2. the default valueOf for view items is the item itself, which is useless for this particular scenario. interpolators will, rightly, return whatever their _actual_ underlying value is, so this sets up a default valueOf function that stringifies the item. I'm pretty sure that's what you'd want for any mustache other than an interpolator.
=> Keep complex bindings in sync - #2444

src/Ractive/prototype/update.js, test/browser-tests/methods/update.js
Was going to put this in `mark`, but it seems like the best way to catch this case is to do it at exactly where the user requests updates to be processed.
=> Resolve unresolveds up the context hierarchy when update is called - #2141

src/model/Model.js, test/browser-tests/plugins/adaptors/basic.js
`applyValue` wasn't checking for a need to create a branch if the value happened to be adapted. See #2467
=> Check for a need to branch on the adaptor path of applyValue too - #2467

src/Ractive.js, src/Ractive/static/keypaths.js, src/model/specials/KeyModel.js, src/shared/keypaths.js, test/__support/js/samples/render.js, test/browser-tests/misc.js
Fixes `{{@key}}` references for escaped keypaths (#1967), and adds four public methods:
```js
Ractive.escapeKey( 'foo.bar' ); // => foo\.bar
Ractive.unescapeKey( 'foo\\.bar' ); // => foo.bar
Ractive.joinKeys( 'foo', 'bar.baz' ); // => foo.bar\.baz
Ractive.splitKeypath( 'foo.bar\\.baz' ); // => [ 'foo', 'bar.baz' ]
```
=> Dot escape 3

src/model/Computation.js, src/model/RootModel.js, src/view/resolvers/ExpressionProxy.js
It looks like this fixes #2477, and may fix part of #2461. The timeline view is a little wonky with what it shows based on when a gc happens, but I've done heap profiling and that is saying that this no longer has a gazillion detached nodes still hanging around.
1. Component mappings are not un-mapped when the component is torn down, which lets the component and all its related gubbins stick around in memory. This adds a teardown, which overlaps with the one in #2462, that handles unregistering mappings so that the components don't hang around. I haven't looked to hard, but it looks like maybe breaking the mapping link will also let the computations get gc'ed when the component is torn down too.
2. ExpressionProxies get a reference to their fragment, create their own Computation …
=> Reduce memory use with this one simple trick! - #2477

src/Ractive/prototype/update.js, test/browser-tests/components/data-and-mappings.js
This is a weird case wherein `update`ing a child keypath doesn't flag a section iterating the parent as dirty across a component boundary and perhaps also not across the boundary in certain circumstances. `applyValue` dirties upstream deps, so it seems reasonable that `update` should also mark upstream deps, does it not?
Linking #2469
=> Notify parent deps on update too - #2469

.babelrc, gobblefile.js, package.json
Using `rollup-plugin-babel` means we can't take advantage of gobble's great caching, and all files are processed by babel every time. By using babel directly (for tests and dev Ractive build), the rebuild time is reduced dramatically.
Cuts down rebuild time to ~3s.
No.
=> Build perf

src/view/items/Section.js, test/__support/js/samples/render.js, test/browser-tests/components/misc.js, test/browser-tests/misc.js, test/browser-tests/twoway.js
Updates `{{#obj}}` to match the new `{{#with obj}}` behavior - only render if `obj` is truthy.
#2024
Yes.
=> render {{#obj}} section only if obj is truthy

src/view/items/element/attribute/getUpdateDelegate.js, src/view/items/element/specials/Option.js, src/view/items/element/specials/Select.js, test/browser-tests/plugins/adaptors/basic.js, test/browser-tests/twoway.js
Removes the forced selection of the first option for bound selects that don't have an option with a matching value.
#2494
No
=> Don't force the first option to be selected in a select with no matching value - #2494

src/model/Model.js, test/browser-tests/plugins/adaptors/basic.js
Adapt during mark if the value identity has changed. Currently only `applyValue` updates wrappers, so changes to the data outside of Ractive don't get a change to update the wrapper (`update`).
This also adds a check in `adapt` to make sure any existing wrapper is torn down before a new one is created.
#2493
No
=> Adapt during mark if necessary - #2493

src/model/Model.js, test/browser-tests/plugins/adaptors/basic.js
There were some extra regressions that got missed the first time around in #2495 because of the way the adaptor there is constructed vs the one in the existing tests. This fully reproduces the case from the adaptor down and fixes the issue.
#2493 
No
=> Missed part of #2493 with #2495

src/Ractive/prototype/observe.js, test/browser-tests/methods/observe.js
Delete references to observers after calling `.cancel()`.
#2499 
No.
=> Delete references to observers after calling .cancel() (closes #2499)

src/Ractive/prototype/shared/makeArrayMethod.js, test/browser-tests/methods/push.js, test/browser-tests/shuffling.js
Ractive will currently branch for you if you `set` an undefined keypath e.g. `r.set( 'foo.0.bar', 'test' )` with an entirely empty data dictionary results in data that looks like `{ foo: [ { bar: 'test' } ] }`. However, if you `push`, `splice`, `unshift`, etc on an undefined keypath, an error is thrown.
This adds a check for `undefined` keypaths and swaps in an empty array instead of throwing an error. This allows regular array methods to be used without having to initialize every keypath that may be used with an array method.
Makes array methods a little more method-call event friendly.
Sort of, but I doubt anyone depends on an exception being thrown when using array methods on undefined keypaths.
=> Let array methods branch too - RFC

src/model/Model.js, test/browser-tests/methods/observe.js
Instead of throwing when a pattern observer tries to check a value type (not object, array, or function) for children, this returns false and has the caller check to see if any children were actually returned.
#2503
Nope
=> Don't throw when a pattern observer encounters a value type - #2503

gobblefile.js, test/browser-tests/misc.js
Adds a step to the build process to add a `Ractive.noConflict()` method that sets the `Ractive` global back to whatever it was when this particular Ractive file loaded and returns the newly removed value e.g. the current Ractive. This only affects those using no module loader.
This is slightly brittle, as it depends on a specific string coming out in the build output, but there is a test canary in the coal mine. 
#2066
Nope
=> Reinstate Ractive.noConflict()

src/Ractive/prototype/observe.js, src/Ractive/prototype/update.js, src/global/runloop.js, src/model/Model.js, src/model/specials/GlobalModel.js, test/browser-tests/init/hooks/misc.js, test/browser-tests/methods/observe.js
This adds a list of pattern observers to `Model`, which is notified when a child is `update`d or `set`. `PatternObserver` then checks to see if a child keypath triggered the change and:
* if there were no keys/children registered, the change happened on the base model, so all matches are collected
* if there were keys registered
* collect the list of registered keypaths
* iterate the list of matches and collect the ones that have a keypath overlapping the registered list
* clear the registered list for the next round
Does this seem like a reasonable approach?
I was going to try to address some of the change event issues here too, but #2421 got a bit too complicated, so I'll punt on that for now.
#2420
No …
=> Only fire pattern observers for changed keypaths - #2420

gobblefile.js
Follow-up to #2515 – because Bublé doesn't have 'helpers', there's no benefit to deferring compilation in order to deduplicate them. This means we can convert ES2015 -> ES5 once, and bundle from there, saving us some time. It *does* mean that non-legacy builds are getting the `.catch` -> `['catch']` transform, but that probably adds about 9 bytes so ¯\ _ (ツ) _ /¯
I've also made the build file a bit DRYer.
=> Faster builds

src/view/helpers/specialAttrs.js, test/browser-tests/attributes.js
Adds a check on style parsing to make sure it's a string.
#2522
Nope.
=> Style attributes shouldn't try to use a boolean value - #2522

package.json, src/Ractive/prototype/shared/makeArrayMethod.js, src/Ractive/prototype/update.js, src/Ractive/static/adaptors/array/index.js, src/Ractive/static/adaptors/magic.js, src/Ractive/static/adaptors/magicArray.js, src/model/Model.js, test/browser-tests/misc.js, test/browser-tests/plugins/adaptors/basic.js, test/browser-tests/plugins/adaptors/magic.js
This:
* consolidates all of the adaptor handling in model into the `adapt` method
* adds a check in `ractive.update` for an adapted parent and delegates the update to the parent if it is adapted
* adds reset methods to all of the provided adaptors that don't cause them to teardown if set with their current value
I think that covers the rest of the weird cases of adaptors, but I'm not sure as I haven't used them extensively. This may also fix some of the magic failures in edge, as it adds a working `reset`. At least I think it is a working `reset`... can anyone comment on the implementation?
Have I missed or completely misunderstood anything?
#2500 
I don't think so
**Reviewers:**
Anyone familiar with how …
=> Adaptor updates - #2500 and maybe more

src/Ractive/prototype/update.js, test/browser-tests/init/hooks/misc.js
Use `get` rather than `retrieve` when registering update changes to ensure computeds actually have a value.
#2520
Nope.
=> Computeds should have a value when being updated - #2520

src/global/TransitionManager.js, test/browser-tests/plugins/transitions.js
This adds a check at the beginning of the transition cycle for nodes that are not up- or downstream of a transitioning node and goes ahead and detaches them immediately.
I'm not entirely sure what this means for nested batches and transitions, but a quick run through looks like it won't release zalgo. I have a feeling ~~that to be 100% accurate this would have to also check parent (and child) manager nodes and transitions, but I also have the feeling that~~ there's no way to cover every corner as parent managers won't be able to check all of their children that may spring into existence.
Thoughts?
#2027
I don't think so.
=> Detach non-transitioning nodes immediately - #2027 - RFC

src/utils/dom.js, src/view/items/Element.js, src/view/items/element/Attribute.js, src/view/items/element/attribute/getUpdateDelegate.js, test/__support/js/samples/render.js, test/browser-tests/attributes.js
This skips `toString` of class and style attributes and moves them the the element level so that the element can aggregate any class and style directives along with the attributes if they exist.
#2537
Sort of... if you depend on exact ordering of attributes in elements. This ends up making classes always come first and styles always come second.
=> merge class and style attributes and directives in toString output

test/browser-tests/events/expression.js
The event expression tests got disabled during the merge. I just want CI to make sure everything is still good when I re-enable.
=> re-enable event expression tests

src/view/resolvers/ReferenceExpressionProxy.js, test/browser-tests/computations.js
In certain interesting scenarios, a reference expression proxy can become a model in another computation, notably with the reference expression is used as context. Turns out reference expressions where not paying attention to capture flags, which makes for sadness when dependencies in the context update. This just adds the capture flag on `ReferenceExpressionProxy.get` to pass along.
#2550
Nerp.
**Reviewers**
@JonDum, if you have a bit of time, could you try this out? I'mma merge it once it goes green, but I want to be sure it handles your more complex case too.
=> Make sure reference expressions capture - #2550

src/global/runloop.js, src/view/Fragment.js, test/browser-tests/render/misc.js
In certain circumstances, bindings and computations can conspire to cause a fragment to be updated while it is updating in a nested batch, which causes issues. This adds a handler that schedules the fragment to be updated again in the base batch so that it doesn't get out of sync. This is hopefully temporary measure, as I think I can refactor the runloop some to simplify this and the other special handling for self-updating observers, bindings, and computations.
#2554
No.
=> Add a temporary extra runloop layer to handle fragments that trigger an update on themselves - #2554

src/model/Model.js, test/browser-tests/computations.js, test/browser-tests/shuffling.js
In certain scenarios where array length is modified by a shuffle, things not _directly_ referencing the length don't get notified that the array has changed, and thus, do not update. This adds tracking for array length (see below) and a check to see if length changes at shuffle in order to notify upstream as `applyValue` would.
For the array length tracking, I plan to use this to allow merging an array into itself. This would make grabbing an array, modifying it in some way _without_ the array wrapper, and getting the changes back into Ractive much simpler. The length is needed to see which children are actually relevant to the merge, since, as it's the same array, there's no way to compare the new and old lengths to build a newIndices object.
**Fixes …
=> Notify upstream during shuffle if array length changes - #2541

src/Ractive/prototype/observe.js, test/browser-tests/components/data-and-mappings.js
Instead of making observers automatically branch to get a model upon creation, this lets them create a resolver to wait around on a model to grow organically (possibly grass-fed and shade-grown) through the unresolved process.
fixes #2142 
Don't think so.
=> Use a reference resolver to allow observers on mappings to be initially ambiguous - #2142

src/Ractive/prototype/observe.js, test/browser-tests/methods/observe.js
Missed a step when handling ambiguity for mapped observers. This adds back the join on implicitly mapped values that are being observer and also plugs a hole that would allow implicit mappings in isolated components if you used an observer.
#2572
Nope.
=> Make sure observers on implicit mappings resolve correctly - #2572

src/Ractive/prototype/fire.js, src/events/fireEvent.js, test/browser-tests/events/bubbling.js
This makes `fire` return its bubble/cancel status so that `<button on-click="@this.fire('someEvent')">` behaves a bit more intuitively. The current workaround is to just add a false expression to the end e.g. `@this.fire('someEvent'), false`. So after this, if you want the event to bubble regardless of the result of the fire, you'd just have to add a true expression e.g. `@this.fire('someEvent'), true`.
#2556 
No
**Reviewers:**
@martypdx
=> Return bubble status from fire for better default fire expression behavior - #2556

src/view/items/element/binding/Binding.js, test/browser-tests/twoway.js
This is a weird one that is caused by behavior that should probably be dropped since laziness is available to help with input validation. At any rate, this checks the see if a binding's model changes to something not set immediately after it is set and before any observers get a chance to fire. If the value is not the same, then the attribute is unlocked so that the binding doesn't get stuck on the old value.
One side effect is that as soon as you press a key that triggers a re-sort on the underlying list, your current box is shuffled off and the new one (actually the same one with a new value, but you get the idea) is sitting there with focus. I think that's better behavior than getting one value stuck in the old box while the new one appears …
=> Check check for binding updates before the observer phase to unlock the attr - #2427

src/view/resolvers/ReferenceExpressionProxy.js, test/browser-tests/computations.js
This updates `ReferenceExpressionProxy` such that instead of triggering an immediate get on all of its models, it waits until the value is actually needed by setting a dirty flag and deferring the actual pull to its own `get`.
#2461
No
=> Make reference expression proxies lazy - #2461

src/Ractive/prototype/transition.js, src/global/TransitionManager.js, src/global/runloop.js, src/shared/getNewIndices.js, src/view/Fragment.js, src/view/RepeatedFragment.js, src/view/items/Element.js, src/view/items/element/Transition.js, test/browser-tests/methods/splice.js, test/browser-tests/methods/transition.js, test/browser-tests/plugins/transitions.js, test/browser-tests/render/components.js
This _should_ fix three outstanding transition issues, one of which was fixed and then broken again in a slightly different way by the recent conditional merge. I say _should_ because transition-related issues are, shall we say, challenging to test.
1. #2463 - this is the one that was fixed and re-broken. This one was caused by some binding happening during transition construction, a time at which parts of the virtual dom are not in place to do resolution. Part II of this issue is dom sticking around past its due date. I did manage to kinda reproduce two or three times it (a tiny percentage) by shaking the crap out of the mouse over the hover trigger. It's not particularly consistent and I couldn't reproduce it with a test rapidly triggering …
=> Transition regression fixes

src/view/resolvers/resolveReference.js, test/browser-tests/components/misc.js
This adds a step to `@rootpath` resolution that pops to the first non-empty (keypath-wise) context to get the keypath. Here's the example:
```handlebars
{{#with foo.bar.baz.bat}}<cmp>{{@rootpath}}</cmp>{{/with}}
```
Without this, the result is an empty string, and with it, the result is `foo.bar.baz.bat`. So, with node info helpers on the event object, you can get the root path to the event context with `event.resolve('@rootpath')`.
#2026
Shouldn't be.
=> Pop to the first actual context when resolving rootpath - fixes #2026

src/model/Model.js, src/view/items/element/Attribute.js, src/view/items/element/attribute/getUpdateDelegate.js, src/view/resolvers/ReferenceExpressionProxy.js, test/browser-tests/methods/updateModel.js
This adds some tracking info to attribute interpolators, if they appear to be relevant and on form elements, that lets `updateFromBindings` iterate the model's list of deps to find any "oneway" bindings from which to update. This is only a fallthrough in the case that there are no twoway bindings.
This covers:
* any element with a `value` attribute (as found in `getUpdateDelegate`)
* `input[type=checkbox|radio]` if the attribute is `checked`
Did I miss any cases?
#1963
No?
=> Check oneway bindings during updateModel if there are no twoways - #1963

src/view/items/element/transitions/createTransitions.js
This adds a timeout of `duration + (delay || 0) + 10` to css transitions in `animateStyle` to force the transition to complete within 10ms of its target. `transitionend` events appear to not be particularly reliable in scenarios where you trigger transitions like a madman.
After aiming the fiddle from #2463 at a build of this branch and about 5 minutes of vigorous mouse wiggling, I'm reasonably confident that this will take care of transition-event-related orphan nodes. I'll probably go ahead and merge this later this afternoon (once it goes green) so that others can get their wiggle on as well to make sure I'm not experiencing the placebo effect.
Side note: I have an idea for a subscription-based software shake weight competitor...
**Fixes the …
=> Wrap animateStyle css transitions in a timeout in case transitionend doesn't fire - #2463

src/view/items/element/Transition.js, src/view/items/element/transitions/createTransitions.js, test/browser-tests/plugins/transitions.js
The timeout safety net on transitions to catch missing transition end (now tested here!) can apparently interfere with quick render/unrender cycles, which kinda makes sense. This adds a complete queue to the transition that cancels the net should the transition complete early because the element is quickly unrendered.
Comment in #2585 by @sabob 
Don't think so.
=> Add a complete queue to transitions to clean up listeners on aborted transitions

src/Ractive/static/adaptors/magic.js, test/browser-tests/plugins/adaptors/magic.js
- preserve `this` by using `.call(this, ...)`
When your model has getters/setters that use `this`, applying magic mode to the model will break them.
None 
**Reviewers:**
Any
=> Make magic mode not break 'this' for the underlying object's getters and setters

perf/tests/jsweb.js, src/global/runloop.js, src/model/ComputationChild.js, src/model/Model.js, src/model/RootModel.js, src/model/specials/GlobalModel.js, src/model/specials/KeyModel.js, src/model/specials/KeypathModel.js, src/model/specials/RactiveModel.js, src/view/items/component/Mapping.js, src/view/items/shared/EventDirective.js, src/view/items/shared/Mustache.js, src/view/resolvers/ExpressionProxy.js, src/view/resolvers/ReferenceExpressionProxy.js, test/browser-tests/shuffling.js
Shuffling is one of the last things that is somewhat slow in edge, primarily because when an array shuffles, everything downstream from that array re-resolves all of its references, which is a pretty slow process. This attempts to make that process slightly smarter by assuming that there are roughly three states for a shuffling rebind: not affected by the shuffle, shuffled, and unknown. The unknown state is kind of a special case that is also used by unmapping and remapping in components to get updates propagated correctly.
When a shuffle kicks off, it registers with the runloop. Then when a rebind fires, if it already has a model, it checks to with the model to see if there is a known new model. If there is, it uses it. If it is known that the model …
=> First pass at slightly smarter (and much faster) shuffling - RFC

src/Ractive/prototype/observe.js, test/browser-tests/methods/observe.js
This set the dirty flag on observers that fire on init so that if they happen to cause their keypath to update, the observer won't fire again. This is a regression from 0.7.3 caused by some shuffling of observer code and a hole in the test suite.
#2594
Quite the opposite.
=> make sure observers that init lock during the init - fixes #2594

src/shared/getNewIndices.js, src/view/RepeatedFragment.js
This adds a check to avoid an unnecessary rebind on fragments that keep their same index when shuffling.
It also adds handling for splices, as opposed to merges, when shuffling where only one block of fragments will be added and/or removed. This avoids moving DOM that doesn't really need to be moved.
Here are the relevant numbers in jsweb perf on my slowish linux box (number in ms):
|test|edge|pr|
|---|---:|---:|
|1. create 1000|750.6|761.6|
|2. swap in 1000 more|36.5|39.0|
|3. append 100|112.7|46.7|
|4. remove first|76.6|71.6|
|5. remove last|36.7|7.4|
The numbers that move a bunch of DOM vary up to 150% depending on the browser's mood when you run the test, but the splice numbers in 3, 4, and 5 are fairly consistently distanced. For instance, the …
=> Avoid unnecessary rebind and optimize splices shufffling - #2599

src/model/Computation.js, src/view/resolvers/ExpressionProxy.js, test/browser-tests/shuffling.js
When shuffling an expression proxy that has unresolved references, the resolvers should be recreated in the new context.
#2602
Nerp.
=> Invalidate resolvers when shuffling an expression - #2602

src/global/TransitionManager.js, test/browser-tests/components/misc.js
This adds guards to nested transaction managers to make sure they don't adjust their parent totals more than once during checks. This bug was introduced when checks started being run multiple times in order to avoid non-transitioning elements getting stuck in the DOM whilst waiting on other unrelated elements to transition out.
See #2578
=> Make sure nested components don't interfere with the transition manager completion

src/view/Fragment.js, src/view/RepeatedFragment.js, src/view/items/Element.js, src/view/items/element/Attribute.js, src/view/items/element/Decorator.js, src/view/items/element/Transition.js, src/view/items/shared/EventDirective.js, src/view/items/shared/Item.js, test/browser-tests/events/misc.js, test/browser-tests/plugins/decorators.js
This adds another view lifecycle step `destroyed` that is triggered after an element is detached during an unrender. Things like decorators and attributes can't be unrendered immediately when their parent element gets the signal to unrender, as that would potentially change the DOM before transitions complete. This was handled for the top-level element, but nested children were not getting notified properly that their decorators, events, and attributes could be torn down safely. With this, the element detach checks to see if it is unrendered, and if it is, it starts the destroyed cycle for its attributes and everything in its fragment.
#2608
No
=> Add a destroyed step to the view for safe hierarchical teardown - #2608

src/Ractive/prototype/observe.js, test/browser-tests/shuffling.js
This adds a check in observers that stops them from firing after `cancel` has been called even if they were already scheduled to run in the current loop. This means that a deferred observer will no longer fire in components that have been removed from the view. So observers that set data on an array that is their context and/or mapping don't create extra array elements as they are spliced out.
#2604
Maybe? I'm not really sure what the prescribed behavior is in this case.
**Reviewers:**
@martypdx @Rich-Harris @MartinKolarik @fskreuz - again, need feedback on whether this is the right way to handle this or if the check should be handled by the dev.
=> Make sure cancelled observers don't fire - #2604

src/Ractive/prototype/observe.js, src/view/items/element/binding/Binding.js, test/browser-tests/methods/observe.js
This adds an `isEqual` check on observers so that observers on computations don't fire multiple times for an unchanged value just because the computation was invalidated.
That by itself is not compatible with two-way bindings and mutating observers, so this also adds a check in the `handleChange` of `Binding` that compares the last value it notified for with the one that it would notify for now. If they are the same, it just skips the notification. That avoids firing the same value multiple times and confusing the observer based on the state of the model/observer and the binding/attribute being in different states while the user still has input control i.e. the control is locked as far as Ractive is concerned so that it doesn't cause the cursor to jump …
=> Check observer value before firing in case a computed is invloved - #2629

src/Ractive/prototype/observe.js, test/browser-tests/methods/observe.js
This adds a check in the dirty handling of pattern observers that allows the change to be processed if there are pending keys registered as changed. What's happening now is multiple `set`s via map only fire the first key changed for the pattern observer because the rest of them are ignored while the observer is dirty.
Would it be better to keep a list of keys seen for this cycle and only allow unseen changes through to avoid issues with two-way binding mutation and pattern observers or pattern observers that mutate their observed value in general? Or is that far enough in left field to safely ignore?
#2631
Don't think so
=> allow pattern observers to get notified multiple times per runloop - #2631

src/view/items/Partial.js, test/browser-tests/partials.js
This records the source of a dynamic literal partial that is used to compare to the new literal partial during update so that the template is not reset unnecessarily. This avoids an error on init when a binding in a child component triggers said partial to update even though there's nothing to update. Note that pre-parsing a template on-the-fly from the computation will cause this check to fail and thus throw the error, but if you're not pre-parsing before the call, I'd say just pass the string and let Ractive handle it.
@JonDum finds interesting bugs :smile:
#2641
No
=> Fun component, binding, and dynamic literal partial bug - #2641

src/view/items/element/binding/Binding.js, src/view/items/element/binding/RadioNameBinding.js, test/browser-tests/twoway.js
Bindings use this.lastValue to track whether or not they change, but grouped bindings with a single value don't really work with that because the group manages the value. This adds a `lastVal` function to bindings that lets the individual implementation decide how to get and set last values.
Question: would it be better to just check for `this.group` and if it's there use it instead of `this.lastValue`? I went the overridden method route because it seems more clear to me what should be happening.
#2638
No
=> Store last value on group for radio name bindings so they don't get stuck - #2638

src/view/items/element/Attribute.js, test/browser-tests/twoway.js
In certain circumstances, notably an update to a model not caused by a set, can cause the last value of a twoway binding to get out of sync. That will cause the binding not to fire a change the next time the user interacts with the element if the interaction causes the new value to be the same as the stale value.
This adds a step in Attribute update that sets the twoway binding last value to the bound interpolator value if the attribute is unlocked, meaning that the update was triggered from somewhere other than the binding.
#2643
Nope
=> Keep twoway binding last val in sync with changes from the model - #2643

src/view/items/element/Transition.js, test/browser-tests/plugins/transitions.js
The match for cleaning up styles was using the event name === "intro", which obviously doesn't match "intro-outro". This swaps the check to use `isIntro`, which is conveniently already set up and a boolean.
#2609 and probably #2632
No
=> Make sure intro-outro on the intro side gets cleaned up as if it were an intro - #2609

src/Ractive/config/defaults.js, test/browser-tests/components/misc.js, test/browser-tests/methods/findAll.js, test/browser-tests/methods/findAllComponents.js, test/browser-tests/misc.js, test/browser-tests/plugins/adaptors/arrays.js, test/browser-tests/plugins/adaptors/magic.js, test/browser-tests/shuffling.js
This defaults modifyArrays to false. The goal is to eventually split magic and array adaptors into plugins, and this is one of the first steps to do so - that has the extra bonus of boosting performance.
The longshot is that if you want to use the non-Ractive flavors of array methods, you would now have to opt in. I believe the Ractive versions have been pushed as the preferred way to handle arrays for a while. What does everyone think? Change it, or leave it as it is for now?
Yes
=> BREAKING: default modifyArrays to false - RFC

src/Ractive/prototype/merge.js, src/model/Model.js, src/view/RepeatedFragment.js, test/browser-tests/methods/merge.js, test/browser-tests/methods/splice.js
Arrays are not currently allowed to merge with themselves, which means you can't modify them in place and then have a nice non-destructive shuffle for the DOM. Since the model representing the array can keep track of its length, and its children keep a reference to their value, the original array can be reconstructed pretty easily. This allows merging arrays with themselves by doing that.
There have been a few questions recently about how to move items in an array without tearing it down in one place and recreating it in another. I think this may be a reasonable way to achieve that.
Nope
=> Allow arrays to be merged with themselves - RFC

src/Ractive/prototype/resetTemplate.js, test/browser-tests/methods/reset.js
When a component doesn't have an actual element as a parent, it is usually rendered with a docfrag, which isn't a proper node. In that case, trying to re-render during a template reset will end up appending the component to a docfrag that is basically disposed causing the component to disappear. This adds a check for component and always looks up the appropriate parent node and anchor if the instance is a component.
#2658
No
**Reviewers:**
@tomekmarchi
=> Handle template resets on components correctly - #2658

src/Ractive/prototype/observe.js, test/browser-tests/methods/observe.js
This sets observers to use their current model value, if available, as the value for future change comparison instead of the model value going into the observer dispatch. The net effect is the observers that change their observed value keep the fresh value cached, whereas current edge gets out of sync because observers can't cause themselves to fire again.
That all sounds right to me, and the test suite is ok with it. Have I missed a corner case somewhere?
#2668
No
**Reviewers:**
@martypdx @kouts
=> Fix another observers modifying the observed value issue - #2668

src/model/LinkModel.js, src/model/ModelBase.js, src/shared/methodCallers.js, test/browser-tests/methods/observe.js
This adds upstream change propagation to links alongside normal model parents so that mapped paths fire observers correctly and notify whatever else may need to be notified. This typically only pops up in scenarios where there is a mapped path that hasn't had the child path accessed yet and the child on the source model changes - because the link child doesn't exist, the source child can't notify it of a change.
#2675
Nope.
=> Make sure upstream propagation hits links too - #2675

src/Ractive/prototype/observe.js, src/model/ModelBase.js, test/browser-tests/methods/observe.js
If there're multiple wildcards in an observer, an unrelated, but partially overlapping keypath may trigger the observer to fire because the current code only considers the first key past the base model. This changes pattern observer notification to get the _whole_ keypath, which allows the observer to make sure that the originating model is actually a whole match and just not a partial match close to the base.
There's a bonus bug here, where a partial match can trigger the observer to dispatch again before the newValues object is reset if the observer callback triggers a fire on a partially matching keypath. That causes a double (or more) fire too. This works around it by not setting up a dispatch if no models actually matched the triggering models for …
=> Include the whole keypath when checking pattern observers - #2682

src/Ractive/prototype/update.js, src/model/Computation.js, src/model/Model.js, src/model/RootModel.js, src/view/resolvers/ExpressionProxy.js, test/__support/js/helpers/Model.js, test/browser-tests/plugins/adaptors/basic.js, test/browser-tests/render/output.js, test/node-tests/toHTML.js
Turns out that there were a handful of issues with various parts of the adaptor support in edge, including the filter parameters not being passed in the correct order. I _think_ I've got just about everything sorted, but it's hard to say. I ran the ractive-ractive test suite against this branch and it only failed on the downstream deep path tests, a merge test, and a reset on child test.
This adds a check for an existing wrapper when trying to adapt a new value on a model, and if one is present, a `newValue` is set on the wrapper so that the reset fires against the right value. Up to now, edge has been trying to reset with the result of `wrapper.get()`. Oops. Fixing that surfaced an interesting bug in the adaptor test suite where `reset` was calling …
=> Try to fix up some outstanding adaptor weirdness - #2693

src/Ractive/config/defaults.js, src/Ractive/config/runtime-parser.js, src/parse/Parser.js, src/parse/_parse.js, src/parse/converters/element/processDirective.js, src/parse/converters/mustache/readSection.js, src/utils/log.js, test/__support/js/samples/parse.js, test/node-tests/basic.js
This does a few things:
1. Add a new parsing option `contextLines`, that when set to:
* `-1` - only shows the message
* `0` - the default - shows the line with the error and the ascii arrow thing beneath at the appropriate character
* any positive integer `num` - get at most `num` lines from above and below the relevant line and wrap them around the line with the ascii arrow thing
2. Makes method call event deprecation stand out more by using the context helper from 1 above to throw out a message for each instance that needs to be updated. This will get really chatty, but un-prefixed methods are most likely going away in 0.9 entirely. It's kinda hard to find these because you can't just search for `decorator` or `transition` like the other deprecated things.
3. Makes proxy events with …
=> Various debug logging changes - RFC - 0.8.1

.travis.yml, scripts/edge-release.sh, src/model/Computation.js, src/model/Model.js, src/view/helpers/processItems.js, src/view/items/shared/EventDirective.js, src/view/resolvers/ExpressionProxy.js
This moves internal tracking of adaptor values from `this.wrapper.value` to `this.wrapperValue` and `this.wrapper.newValue` to `this.newWrapperValue`. I _think_ this will fix the issues with the backbone adaptor, and we probably shouldn't be doing stuff like that anyway.
This also stops edge deployment through surge. I'm hoping to get automated npm deployment set up soon. There's a helper script that I'll test out with this build to see if automated build publishing will work once I figure out how to safely include an npm auth token.
_Hopefully_ #2714
No
=> Don't hang internal use properties off of adaptor objects - #2714

package.json, scripts/test.sh, test/node-tests/.eslintrc, test/node-tests/basic.js, test/node-tests/components.js, test/node-tests/getCSS.js, test/node-tests/index.js, test/node-tests/parse.js, test/node-tests/toCSS.js, test/node-tests/toHTML.js
Convert node tests to QUnit. 
- Less cognitive overhead when writing tests. You need not write tests in two different ways.
- Consistent setup. Similar to the browser, test code can assume QUnit and Ractive are present already.
- The `qunit-cli` module has a very nice colored checklist report format.
I could have gone the other way, write the browser tests in mocha. But QUnit is both runner and assertion lib, API is very consistent between node and browser... and there's lesser node tests to update. 😁 
Nope. But it is breaking some tests for some unknown reason.
Anyone curious.
=> Node tests to use QUnit

src/Ractive/initialise.js, src/Ractive/render.js, test/browser-tests/init/config.js
This allows a target element to be specified at init with `target` as well as `el` for consistency sake. We don't use abbreviations anywhere else, and this brings in a way to set el that matches the rest of the config params.
#1848
Maybe, if you have `target` as a property on a component or instance.
=> Allow target as a config alias for el - #1848

package.json
Adds a clean script in npm removing `.gobble`, `.gobble-build`, `build` and `tmp`.
No
Yes, if you want to add anything or tell me I'm just lazy. 😄
=> Add clean script, because it's handy.

src/parse/converters/expressions/primary/literal/objectLiteral/keyValuePair.js, src/parse/converters/expressions/primary/literal/readArrayLiteral.js, src/parse/converters/expressions/primary/readReference.js, src/parse/converters/expressions/readMemberOrInvocation.js, src/parse/converters/expressions/shared/patterns.js, src/parse/converters/expressions/shared/readExpressionList.js, src/parse/utils/flattenExpression.js, test/__support/js/samples/parse.js, test/browser-tests/computations.js
In the process of working on the tutorial site, I had the desire to have an options object for a decorator that included the keys from another object. Of course, you can already do that with `Object.assign` where available, but the es201x syntax is so much better: `{ foo: 'bar', baz: 'bat', ...someObj, ...otherObj }` === `Object.assign( {}, { foo: 'bar', baz: 'bat' }, someObj, otherObj )`. (_Note_: the empty first object is only there for equivalence to transpiled code - it's not strictly necessary) We already support spread args for calls, but not lists and objects. I also needed a break from docs.
This adds support for spread arrays `[ foo, bar, ...baz, bat, bip, ...bop ]`, spread objects from above, and simplifies the spread arguments code a bit by using the spread array helpers. All …
=> Add support for spread arrays and objects and merge with call spreads - RFC - 0.9

src/Ractive/construct.js, src/Ractive/static/adaptors/array/patch.js, test/browser-tests/plugins/adaptors/basic.js
This checks for a parent instance during config, and if there is one, copies its adaptors to the end of the instance adaptor list. Apparently this changed some time between 0.7 and 0.8. This is my first foray into the construct code, so I'm not positive this is the best way to handle this.
There's also some question as to whether or not components should inherit their parent's adaptors. I think it makes sense for an app that's working with special data to have the component be able to work with it as well. Mapping aren't affected, since the mapping defers wrapping to the source, but any other setting of data is.
This also makes the prototype overrides on arrays from the builtin array adaptor configurable per #2721.
#2723 #2721
No?
Anyone familiar with adaptors.
=> Inherit parent adaptors when initializing a component - #2723

src/Ractive/config/defaults.js, src/model/Computation.js, src/model/ComputationChild.js, src/view/resolvers/ExpressionProxy.js, test/browser-tests/computations.js, test/browser-tests/twoway.js
This is a port of #2331 to edge. It actually takes less code now :smile:
**Definition**: For this PR, "computed" means a value that isn't directly in data, so any `computed` entries from instance init and any expression in the template.
Starting with 0.8, binding/setting in children of computed values e.g. `<input value="{{computed.some.child}}" />` was disallowed because it can cause references outside of the computation to get out of sync with their model. See #2123 for more details.
This introduces a new flag `syncComputedChildren`, which defaults to false, that sets up children of computed paths to be mutable. When a child mutates, it causes an updated on all of the computation's dependencies, which makes sure any other references outside of the computation stay in sync. That should …
=> Binding and/or mutation of children of computations - take two - RFC

src/view/items/element/attribute/getUpdateDelegate.js, src/view/items/element/binding/CheckboxNameBinding.js, src/view/items/element/binding/RadioNameBinding.js, src/view/items/element/specials/Input.js, src/view/items/element/specials/Option.js, src/view/items/element/specials/Select.js, test/browser-tests/select.js, test/browser-tests/twoway.js
**NOT READY TO MERGE**
It's just to see if that's the right way to go. It needs to work for radios and checkboxes too.
This tries to fix the problem when binding objects in your <select> and the two objects that it compares are different using a simple '==' but for the developer perspective they are the same. So the developer is able to define `<select value-comparator=X">`, X being a string or a function reference to compare the two objects.
#2545
NO
=> <select> comparator attribute
