ractivejs/ractive

- src/Ractive/static/adaptors/magic.js
- src/viewmodel/prototype/clearCache.js
- src/viewmodel/prototype/mark.js
- src/viewmodel/prototype/set.js
This was bugging the crap out of me while looking for the issue in https://github.com/ractivejs/ractive/issues/1639. Double negatives are confusing.
> Switched 'dontTeardownWrapper' to 'teardownWrapper'

- src/utils/parseJSON.js
> work around 6to5 transpilation issue

- src/parse/_parse.js
- test/testdeps/samples/render.js
Nice easy fix. My kind of bug
:bug: :gun:
> if...else works with conditional attributes (closes #1662)

- src/config/types.js
- src/parse/_parse.js
- src/parse/converters/mustache/readSection.js
- src/parse/converters/mustache/section/readElseIf.js
- test/__tests/render.js
- test/testdeps/samples/render.js
**not ready for merge**
see #1631 and #1668
> alternative {{elseif ...}}

- src/viewmodel/helpers/getUpstreamChanges.js
- test/__tests/observe.js
> prevent adding upstream changes for notify that are already in changes

- src/extend/_extend.js
- test/__tests/init/initialisation.js
> Allow multiple extend arguments

- src/Ractive/config/custom/css/css.js
- src/Ractive/initialise.js
- src/Ractive/prototype/render.js
- src/Ractive/prototype/unrender.js
- src/extend/_extend.js
- src/global/css.js
- test/__tests/css.js
> Encapsulated style fix

- src/parse/converters/element/readAttribute.js
- src/parse/converters/readElement.js
- src/virtualdom/items/Component/initialise/createInstance.js
- src/virtualdom/items/Element/prototype/toString.js
- test/__tests/components.js
- test/testdeps/samples/parse.js
- test/testdeps/samples/render.js
Fat fingered the first submission. Meh.
> Various attribute handling adjustments

- src/viewmodel/prototype/map.js
- test/__tests/components.js
> Check resolved status before unregister of mapping

- src/virtualdom/items/Element/Binding/Binding.js
- test/__tests/twoway.js
> add warning for ambiguous references (#1692)

- src/shared/keypaths.js
- test/__tests/observe.js
@martypdx does this seem like a good fix for #1592?
> test and fix for #1592

- src/shared/getNewIndices.js
- src/viewmodel/prototype/smartUpdate.js
- src/virtualdom/items/shared/Resolvers/ReferenceExpressionResolver/ReferenceExpressionResolver.js
- test/__tests/arrayMethods.js
> fix various splice-related bugs

- src/virtualdom/Fragment/prototype/rebind.js
- src/virtualdom/items/Section/prototype/setValue.js
- test/__tests/arrays.js
> Unwanted context

- src/viewmodel/Computation/Computation.js
- test/__tests/computations.js
This fixes a long-standing bug (#1359) which could arise if you made a change inside a computation that led to the computation being called again. The usual reason was `array.sort()`, when `modifyArrays` is `true`.
This PR prevents the resulting wackiness, and also prints a warning to help guide developers away from this error.
> return correct value from self-calling computation, and warn - fixes #1359

- src/virtualdom/items/Element/Binding/Binding.js
- test/__tests/twoway.js
> warn if two-way binding is attempted with a "special" keypath e.g. @key

- appveyor.yml
- package.json
- scripts/build.sh
> See if appveyor will succeed on the second run too

- src/virtualdom/items/Partial/_Partial.js
- test/__tests/partials.js
> Only unrender partial fragment if partial has been rendered

- src/Ractive.js
- test/__tests/misc.js
> make Ractive.DEBUG writable

- bootstrap-phantomjs-debug.js
- src/Ractive/config/config.js
- test/__tests/init/initialisation.js
See discussion [starting here](https://github.com/ractivejs/ractive/issues/1853#issuecomment-84411137)
> Warn and ignore functions supplied for standard options

- src/utils/getPotentialWildcardMatches.js
> Substitute Array.prototype.map by a raw for loop

- src/Ractive/initialise.js
- src/Ractive/prototype/observe/getObserverFacade.js
- src/Ractive/prototype/teardown.js
- src/shared/methodCallers.js
- src/virtualdom/items/Component/prototype/unbind.js
- test/__tests/observe.js
> cancel all observers when instance is torn down (#1865)

- src/Ractive/prototype/resetTemplate.js
- src/model/Computation.js
- src/model/Model.js
- src/parse/converters/expressions/primary/readReference.js
- src/parse/converters/readPartialDefinitionSection.js
- src/view/Fragment.js
- src/view/helpers/processItems.js
- src/view/items/Component.js
- src/view/items/Partial.js
- src/view/items/Triple.js
- src/view/items/shared/Mustache.js
- src/view/resolvers/resolveAmbiguousReference.js
- src/view/resolvers/resolveReference.js
- test/__tests/adaptors.js
- test/__tests/arrays.js
- test/__tests/computations.js
- test/__tests/partials.js
- test/__tests/reset.js
There are a few things in here that I'm not sure about... I'll throw comments inline.
> Take care of a few arboretum-getters test failures

- gobblefile.js
Please see:
https://github.com/ractivejs/ractive/issues/2094
> Issue #2094 Added Windows Path Matching for Version Replace

- src/config/visibility.js
- src/shared/Ticker.js
- src/view/items/element/Transition.js
- src/view/items/element/transitions/createTransitions.js
- test/__tests/transitions.js
Various fixes to transitions (the least well tested part of this library?) – stuff that broke with #2022.
> Transitions

- src/view/RepeatedFragment.js
Ref: http://jsbin.com/basapeqale/2/edit?html,js,output
This relates to #2103
> #2103 - Fix bug with repeated fragment updating the wrong node

- src/view/items/shared/EventDirective.js
- test/__tests/events.js
ran into this trying to get our code to run on 0.8
cheers
> Model fn bindings

- src/view/RepeatedFragment.js
- test/__tests/render.js
> Unrender all section fragments if type changes (#2054)

- src/view/RepeatedFragment.js
Couldn't explicitly recreate via test (probably because of #2118), but this seems reasonable to ensure fix for #2101
> Initialize iterations to empty array (#2101)

- src/view/items/shared/Mustache.js
- test/__tests/arrayMethods.js
> check for this.model existence when rebinding - fixes #2114

- src/model/ComputationChild.js
- test/browser-tests/computations.js
> capture ComputationChild dependencies - fixes #2132

- src/model/Model.js
- test/__support/js/samples/render.js
> Better detection of existing keys in models

- perf/tests/events.js
- perf/tests/render-iterate.js
- src/parse/converters/utils/getLowestIndex.js
Reduces the parse time by about 800%.
> Improve parser performance

- src/view/resolvers/ExpressionProxy.js
- test/browser-tests/computations.js
This is unfamiliar territory for me, so is this a proper fix?
> Make expression proxies notify their deps when their bits resolve - #2214

- src/parse/converters/expressions/primary/readReference.js
- test/__support/js/samples/render.js
> support Object, String, Number and Boolean in templates (fixes #2247)

- src/view/items/shared/Mustache.js
- test/browser-tests/rebind.js
> prevent premature computation

- src/view/resolvers/ExpressionProxy.js
- test/browser-tests/components/data-and-mappings.js
Just a failing test case for now. See #2261
> Computations that depend on mapped computations

- src/view/items/shared/EventDirective.js
- test/browser-tests/events/method-calls.js
> Auto prevent and stop event when method call returns false (#2301)

- src/model/Model.js
- test/browser-tests/methods/observe.js
> throw error when getting foo.* if foo is not array/object/function

- src/view/items/element/ConditionalAttribute.js
if str is empty, let's not waist time manipulating dom elements
> Update ConditionalAttribute.js for Performance

- src/Ractive/static/interpolators.js
- test/browser-tests/methods/animate.js
> fix object animations with identical properties

- src/view/items/element/binding/selectBinding.js
- test/browser-tests/twoway.js
Hi all,
This pull request allows checkboxes to bind on both name and checked attributes.
Raised in issue: #1749
Kind regards
Bob
> checkbox can bind on name and checked - gh-1749

- src/Ractive/prototype/animate.js
- test/browser-tests/methods/animate.js
Fixes [this bug](http://jsfiddle.net/rich_harris/w7jnLtvn/)
> pass instance to getOptions inside Ractive$animate

- src/Ractive/prototype/on.js
Just learning Ractive by reading its source code. :)
> typo in a comment

- src/view/items/Element.js
- src/view/items/element/specials/Select.js
I'm tired of looking at the enhancement tests failing, so I split the fix from #2369 out. Apparently Firefox is a real leader when it comes to correct behavior, because now Chrome 49 dies on those two tests too.
Fixes #2273
> Fix for enhancement and selects - #2273

- appveyor.yml
Removes node `0.10` and `1.0` from AppVeyor.
> Update AppVeyor config

- .jshintrc
- gobblefile.js
- src/Ractive/initialise.js
- src/global/css.js
- src/model/Computation.js
- src/utils/getSelectedOptions.js
- src/view/items/element/binding/MultipleSelectBinding.js
- src/view/items/element/binding/SingleSelectBinding.js
- src/view/items/element/specials/Select.js
- src/view/items/triple/insertHtml.js
- test/.jshintrc
- test/__support/js/test-config.js
- test/browser-tests/getCSS.js
- test/browser-tests/init/hooks/misc.js
- test/browser-tests/methods/toCSS.js
- test/browser-tests/misc.js
- test/browser-tests/polyfills.js
Trying to get tests to pass in all browsers; current status:
> Tests & bug fixes

- src/model/RootModel.js
- test/browser-tests/methods/update.js
This adds a step to root model mark that iterates the mappings and marks them as well.
#2574
Don't think so.
**Reviewers:**
Please.
> Mark mappings along with root viewmodels - fixes #2574

- src/README.md
- src/model/README.md
- src/parse/README.md
- src/view/README.md
I cleaned _at_ some of my notes and popped them into a readme that tries to give a general overview of the major parts of Ractive, what they do, and how they're arranged in the src tree. I'm not at all a writer of words, so it's my usual rambley run-on text, but hopefully it makes it a little easier to understand what Ractive does under the hood. I hope to add a few more detailed breakdowns in some of the other child directories soon, but I thought I'd throw this into a PR/branch for feedback and possibly some collaboration.
So, feedback and pushes welcome! :smile:
> Attempt to document design and source layout

- test/browser-tests/events/method-calls.js
The tests are always greener on the other side.
> Trying to fix appveyor

- src/Ractive/config/custom/css/transform.js
> Remove multiline comments when transforming css (#2683)
